name: Elevators
version: '${project.version}'
main: net.forestfire.elevators.Main
api-version: 1.18
authors: [ Pecacheu ]
description: Adds Working Elevators to Minecraft!
commands:
  elev:
    description: Reload The Plugin.
    usage: /elev reload
    permission: elevators.reload
    permission-message: You don't have permission to do that!
permissions:
  elevators.use:
    default: true
  elevators.create:
    default: op
  elevators.reload:
    default: op