name: Elevators
version: '${project.version}'
main: net.forestfire.elevators.Main
api-version: 1.18
authors: [ Pecacheu ]
description: Adds Working Elevators to Minecraft!
commands:
  elev:
    description: Reload the plugin or reset last used elevator.
    usage: /elev <list|reload|reset>
    permission: elevators.reload
permissions:
  elevators.use:
    default: true
  elevators.create:
    default: op
  elevators.reload:
    default: op